artifacts_root: artifacts

data_ingestion:
 root_dir : artifacts/data_ingestion
 source_URL: https://github.com/richardmukechiwa/Datasets/raw/refs/heads/main/credit_risk.zip
 local_data_file: artifacts/data_ingestion/credit_risk.zip
 unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir : artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/credit_risk.csv
  STATUS_FILE: artifacts/data_validation/status.txt

